### ISSUE TITLE
Please fix up the accessibility issues

### ISSUE THREAD

**Issue by mgifford** [JordanHatch/civictech.club#52]
Many of the images should probably just have `alt=""` but there are some other issues too. These are just from Accessibility Insights. 

![Screenshot of errors on the page](https://user-images.githubusercontent.com/116832/203460171-559d8366-ada9-4167-9961-dca54068ff9b.png)
[FastPass_20221122_civictechclubcivicte.zip](https://github.com/JordanHatch/civictech.club/files/10072524/FastPass_20221122_civictechclubcivicte.zip)

**Comment by JordanHatch** [comment]
@mgifford Thanks for this - all of these should be fixed in the changes in 4b70346 🙂

**Comment by mgifford** [comment]
Nice. Thanks for fixing that all up ASAP!
